version: "2"
services:
  java:
    build: ./java
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - 8888:8080

  node:
    build: ./node
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - 8887:3000

  dotnet:
    build: ./dotnet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - 8886:5000

  frontend:
    build: ./frontend
    ports:
      - 8000:3000
